-- Plugins in this setup that Base46 does not ship integrations for.
-- Every color comes from the selected palette, including for light themes.
local c = require("base46").get_theme_tb("base_30")
local h = {
  NormalNC = { link = "Normal" },
  MsgArea = { fg = c.white },
  StatusLine = { fg = c.white, bg = c.statusline_bg },
  StatusLineNC = { fg = c.grey_fg, bg = c.statusline_bg },
  NeoTreeNormal = { fg = c.white, bg = c.darker_black },
  NeoTreeNormalNC = { link = "NeoTreeNormal" },
  NeoTreeEndOfBuffer = { fg = c.darker_black, bg = c.darker_black },
  NeoTreeWinSeparator = { fg = c.line, bg = c.darker_black },
  NeoTreeDirectoryName = { fg = c.folder_bg },
  NeoTreeDirectoryIcon = { fg = c.folder_bg },
  NeoTreeRootName = { fg = c.blue, bold = true },
  NeoTreeFileName = { fg = c.white },
  NeoTreeFileNameOpened = { fg = c.green },
  NeoTreeCursorLine = { fg = c.white, bg = c.one_bg2 },
  NeoTreeIndentMarker = { fg = c.one_bg3 },
  NeoTreeExpander = { fg = c.grey_fg },
  NeoTreeDotfile = { fg = c.grey_fg },
  NeoTreeGitAdded = { fg = c.green },
  NeoTreeGitModified = { fg = c.yellow },
  NeoTreeGitDeleted = { fg = c.red },
  NeoTreeGitConflict = { fg = c.orange },
  NeoTreeGitUntracked = { fg = c.teal },
  NeoTreeGitIgnored = { fg = c.grey_fg },
  NeoTreeFloatBorder = { link = "FloatBorder" },
  NeoTreeFloatTitle = { link = "FloatTitle" },
  NoiceCmdline = { fg = c.white },
  NoiceCmdlinePopup = { fg = c.white, bg = c.darker_black },
  NoiceCmdlinePopupBorder = { fg = c.blue, bg = c.darker_black },
  NoiceCmdlinePopupTitle = { fg = c.black, bg = c.blue },
  NoiceCmdlineIcon = { fg = c.blue },
  NoiceCmdlineIconSearch = { fg = c.yellow },
  NoiceCmdlinePopupBorderSearch = { fg = c.yellow, bg = c.darker_black },
  NoiceConfirm = { fg = c.white, bg = c.darker_black },
  NoiceConfirmBorder = { fg = c.blue },
  SnacksNormal = { fg = c.white, bg = c.darker_black },
  SnacksNormalNC = { link = "SnacksNormal" },
  SnacksBackdrop = { bg = c.black },
  SnacksPicker = { fg = c.white, bg = c.darker_black },
  SnacksPickerBorder = { fg = c.line, bg = c.darker_black },
  SnacksPickerCursorLine = { fg = c.white, bg = c.one_bg2 },
  SnacksPickerMatch = { fg = c.blue, bold = true },
  SnacksInputNormal = { link = "NormalFloat" },
  SnacksInputBorder = { link = "FloatBorder" },
  SnacksDashboardNormal = { link = "Normal" },
  SnacksDashboardHeader = { fg = c.blue },
  SnacksDashboardFooter = { fg = c.grey_fg },
  SnacksDashboardDesc = { fg = c.white },
  SnacksDashboardKey = { fg = c.red },
  SnacksDashboardIcon = { fg = c.blue },
  SnacksDashboardSpecial = { fg = c.yellow },
  SnacksDashboardFile = { fg = c.white },
  SnacksDashboardDir = { fg = c.grey_fg },
  SnacksIndent = { fg = c.one_bg2 },
  SnacksIndentScope = { fg = c.grey },
  MiniIconsAzure = { fg = c.blue },
  MiniIconsBlue = { fg = c.blue },
  MiniIconsCyan = { fg = c.cyan },
  MiniIconsGreen = { fg = c.green },
  MiniIconsGrey = { fg = c.light_grey },
  MiniIconsOrange = { fg = c.orange },
  MiniIconsPurple = { fg = c.purple },
  MiniIconsRed = { fg = c.red },
  MiniIconsYellow = { fg = c.yellow },
  -- Correct historical casing mismatches in upstream's DAP integration.
  DapUIScope = { fg = c.cyan },
  DapUIType = { fg = c.purple },
  DapUIValue = { fg = c.white },
  DapUIVariable = { fg = c.white },
  DapUISource = { fg = c.purple },
  DapBreakpointRejected = { fg = c.orange },
  DapUIBreakpointsCurrentLine = { fg = c.green, bold = true },
}
for _, level in ipairs({ "Error", "Warn", "Info", "Hint" }) do
  h["NeoTree" .. level] = { link = "Diagnostic" .. level }
end
for name, value in pairs(require("config.theme-bufferline").highlights()) do
  local group = "BufferLine" .. name:gsub("^%l", string.upper):gsub("_(%l)", string.upper)
  h[group] = value
end
return h
