-- Generated by Wallust for Neovim
return {
  background = "#1C2021",
  foreground = "#EDF7D8",

  color0  = "#424647",
  color1  = "#2A523B",
  color2  = "#2A523B",
  color3  = "#5B8564",
  color4  = "#5B8564",
  color5  = "#5B8564",
  color6  = "#98AD6D",
  color7  = "#DDEBC0",
  color8  = "#9AA486",
  color9  = "#386D4F",
  color10 = "#386D4F",
  color11 = "#79B186",
  color12 = "#79B186",
  color13 = "#79B186",
  color14 = "#CBE791",
  color15 = "#DDEBC0",
}
