-- Generated by Wallust for Neovim
return {
  background = "#141516",
  foreground = "#C3C6C6",

  color0  = "#3B3C3D",
  color1  = "#0E1013",
  color2  = "#0E1013",
  color3  = "#111316",
  color4  = "#111417",
  color5  = "#3B4142",
  color6  = "#3E4445",
  color7  = "#A0A5A5",
  color8  = "#707374",
  color9  = "#121519",
  color10 = "#121519",
  color11 = "#16191D",
  color12 = "#171B1F",
  color13 = "#4F5758",
  color14 = "#535B5C",
  color15 = "#A0A5A5",
}
