-- Auto-generated by DMS - do not edit manually
-- Migrated from binds.conf to the Hyprland 0.55+ Lua config format.

-- === DMS actions / media / screenshots ===
hl.bind("ALT + Insert",         hl.dsp.exec_cmd("dms screenshot full"))
hl.bind("CTRL + ALT + Delete",  hl.dsp.exec_cmd("dms ipc call processlist focusOrToggle"))
hl.bind("CTRL + XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call mpris decrement 3"), { locked = true, repeating = true })
hl.bind("CTRL + XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call mpris increment 3"), { locked = true, repeating = true })
hl.bind("CTRL + Insert",        hl.dsp.exec_cmd("dms screenshot window"))
hl.bind("Print",                hl.dsp.exec_cmd("dms screenshot"))
hl.bind("SUPER + ALT + L",      hl.dsp.exec_cmd("dms ipc call lock lock"))
hl.bind("SUPER + M",            hl.dsp.exec_cmd("dms ipc call processlist focusOrToggle"))
hl.bind("SUPER + N",            hl.dsp.exec_cmd("dms ipc call notifications toggle"))
hl.bind("SUPER + SHIFT + N",    hl.dsp.exec_cmd("dms ipc call notepad toggle"))
hl.bind("SUPER + SHIFT + Slash", hl.dsp.exec_cmd("dms ipc call keybinds toggle hyprland"))
hl.bind("SUPER + SHIFT + W",    hl.dsp.exec_cmd("dms ipc call window-rules toggle"))
hl.bind("SUPER + TAB",          hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"))
hl.bind("SUPER + V",            hl.dsp.exec_cmd("dms ipc call clipboard toggle"))
hl.bind("SUPER + X",            hl.dsp.exec_cmd("dms ipc call powermenu toggle"))
hl.bind("SUPER + Y",            hl.dsp.exec_cmd("dms ipc call dankdash wallpaper"))
hl.bind("SUPER + comma",        hl.dsp.exec_cmd("dms ipc call settings focusOrToggle"))
hl.bind("SUPER + D",            hl.dsp.exec_cmd("dms ipc call spotlight toggle"))
hl.bind("SUPER + W",            hl.dsp.exec_cmd("dms ipc call wallpaperCarousel toggle"))

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call audio decrement 3"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("dms ipc call audio micmute"), { locked = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("dms ipc call audio mute"), { locked = true })
hl.bind("XF86AudioNext",        hl.dsp.exec_cmd("dms ipc call mpris next"), { locked = true })
hl.bind("XF86AudioPause",       hl.dsp.exec_cmd("dms ipc call mpris playPause"), { locked = true })
hl.bind("XF86AudioPlay",        hl.dsp.exec_cmd("dms ipc call mpris playPause"), { locked = true })
hl.bind("XF86AudioPrev",        hl.dsp.exec_cmd("dms ipc call mpris previous"), { locked = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call audio increment 3"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("dms ipc call brightness decrement 5 \"\""), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("dms ipc call brightness increment 5 \"\""), { locked = true, repeating = true })

-- === Workspaces 1-9 ===
for i = 1, 9 do
    hl.bind("SUPER + " .. i,         hl.dsp.focus({ workspace = tostring(i) }))
    hl.bind("SUPER + SHIFT + " .. i, hl.dsp.window.move({ workspace = tostring(i) }))
end

-- Move active window to relative workspace
hl.bind("SUPER + CTRL + I",          hl.dsp.window.move({ workspace = "e-1" }))
hl.bind("SUPER + CTRL + U",          hl.dsp.window.move({ workspace = "e+1" }))
hl.bind("SUPER + CTRL + down",       hl.dsp.window.move({ workspace = "e+1" }))
hl.bind("SUPER + CTRL + mouse_down", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind("SUPER + CTRL + mouse_up",   hl.dsp.window.move({ workspace = "e-1" }))
hl.bind("SUPER + CTRL + up",         hl.dsp.window.move({ workspace = "e-1" }))
hl.bind("SUPER + SHIFT + I",         hl.dsp.window.move({ workspace = "e-1" }))
hl.bind("SUPER + SHIFT + Page_Down", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind("SUPER + SHIFT + Page_Up",   hl.dsp.window.move({ workspace = "e-1" }))
hl.bind("SUPER + SHIFT + U",         hl.dsp.window.move({ workspace = "e+1" }))

-- Switch to relative workspace
hl.bind("SUPER + I",          hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + Page_Down",  hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + Page_Up",    hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + U",          hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- === Resize ===
-- NOTE: hl.window.resize takes pixel values only (no % / "exact"). The percentage
-- binds below were approximated for a 1920x1080 monitor (10% = 192 / 108 px).
hl.bind("SUPER + CTRL + F",      hl.dsp.window.resize({ x = 1920, y = 1080, relative = false }))
hl.bind("SUPER + SHIFT + equal", hl.dsp.window.resize({ x = 0,   y = 108,  relative = true }), { repeating = true })
hl.bind("SUPER + SHIFT + minus", hl.dsp.window.resize({ x = 0,   y = -108, relative = true }), { repeating = true })
hl.bind("SUPER + equal",         hl.dsp.window.resize({ x = 192, y = 0,    relative = true }), { repeating = true })
hl.bind("SUPER + minus",         hl.dsp.window.resize({ x = -192, y = 0,   relative = true }), { repeating = true })

-- === Focus monitors ===
hl.bind("SUPER + CTRL + H",     hl.dsp.focus({ monitor = "l" }))
hl.bind("SUPER + CTRL + J",     hl.dsp.focus({ monitor = "d" }))
hl.bind("SUPER + CTRL + K",     hl.dsp.focus({ monitor = "u" }))
hl.bind("SUPER + CTRL + L",     hl.dsp.focus({ monitor = "r" }))
hl.bind("SUPER + CTRL + left",  hl.dsp.focus({ monitor = "l" }))
hl.bind("SUPER + CTRL + right", hl.dsp.focus({ monitor = "r" }))

-- === Focus windows ===
hl.bind("SUPER + End",  hl.dsp.focus({ window = "last" }))
hl.bind("SUPER + Home", hl.dsp.focus({ window = "first" }))
hl.bind("SUPER + H",    hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + J",    hl.dsp.focus({ direction = "down" }))
hl.bind("SUPER + K",    hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + L",    hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + down",  hl.dsp.focus({ direction = "down" }))
hl.bind("SUPER + left",  hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + right", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + up",    hl.dsp.focus({ direction = "up" }))

-- === Move window to monitor ===
hl.bind("SUPER + SHIFT + CTRL + H",     hl.dsp.window.move({ monitor = "l" }))
hl.bind("SUPER + SHIFT + CTRL + J",     hl.dsp.window.move({ monitor = "d" }))
hl.bind("SUPER + SHIFT + CTRL + K",     hl.dsp.window.move({ monitor = "u" }))
hl.bind("SUPER + SHIFT + CTRL + L",     hl.dsp.window.move({ monitor = "r" }))
hl.bind("SUPER + SHIFT + CTRL + down",  hl.dsp.window.move({ monitor = "d" }))
hl.bind("SUPER + SHIFT + CTRL + left",  hl.dsp.window.move({ monitor = "l" }))
hl.bind("SUPER + SHIFT + CTRL + right", hl.dsp.window.move({ monitor = "r" }))
hl.bind("SUPER + SHIFT + CTRL + up",    hl.dsp.window.move({ monitor = "u" }))

-- === Move window within layout ===
hl.bind("SUPER + SHIFT + H",     hl.dsp.window.move({ direction = "left" }))
hl.bind("SUPER + SHIFT + J",     hl.dsp.window.move({ direction = "down" }))
hl.bind("SUPER + SHIFT + K",     hl.dsp.window.move({ direction = "up" }))
hl.bind("SUPER + SHIFT + L",     hl.dsp.window.move({ direction = "right" }))
hl.bind("SUPER + SHIFT + down",  hl.dsp.window.move({ direction = "down" }))
hl.bind("SUPER + SHIFT + left",  hl.dsp.window.move({ direction = "left" }))
hl.bind("SUPER + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind("SUPER + SHIFT + up",    hl.dsp.window.move({ direction = "up" }))

-- === Mouse move / resize ===
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(),   { description = "Move window" })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { description = "Resize window" })

-- === Launchers ===
hl.bind("SUPER + ALT + M",   hl.dsp.exec_cmd("java -jar /home/alamin/TLauncher.jar"))
hl.bind("SUPER + apostrophe", hl.dsp.exec_cmd("/home/alamin/.config/hypr/my-hypr/scripts/ScreenRecord.sh area"))
hl.bind("SUPER + B",         hl.dsp.exec_cmd("thorium-browser"))
hl.bind("SUPER + C",         hl.dsp.exec_cmd("code"))
hl.bind("SUPER + E",         hl.dsp.exec_cmd("nautilus"))
hl.bind("SUPER + G",         hl.dsp.exec_cmd("/home/alamin/.config/hypr/my-hypr/scripts/GameMode.sh"))
hl.bind("SUPER + O",         hl.dsp.exec_cmd("flatpak run md.obsidian.Obsidian"))
hl.bind("SUPER + Return",    hl.dsp.exec_cmd("ghostty"))
hl.bind("SUPER + semicolon", hl.dsp.exec_cmd("/home/alamin/.config/hypr/my-hypr/scripts/ScreenRecord.sh full"))

-- === Window / session management ===
hl.bind("SUPER + SHIFT + E", hl.dsp.exit())
hl.bind("SUPER + F",         hl.dsp.window.fullscreen({ mode = "maximized" }))
hl.bind("SUPER + Q",         hl.dsp.window.close())
hl.bind("SUPER + R",         hl.dsp.layout("togglesplit"))
hl.bind("SUPER + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }))
hl.bind("SUPER + SHIFT + T", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + bracketleft",  hl.dsp.layout("preselect l"))
hl.bind("SUPER + bracketright", hl.dsp.layout("preselect r"))
hl.bind("SUPER + ALT + P",   hl.dsp.exec_cmd("dms ipc call fullscreenPowerMenu toggle"))
hl.bind("SUPER + SHIFT + G", hl.dsp.group.toggle())
hl.bind("SUPER + SHIFT + Q", hl.dsp.window.kill())
