-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(29a298)",
			inactive_border = "rgb(576d74)",
		},
	},
	group = {
		col = {
			border_active = "rgb(29a298)",
			border_inactive = "rgb(576d74)",
			border_locked_active = "rgb(db302d)",
			border_locked_inactive = "rgb(576d74)",
		},
		groupbar = {
			col = {
				active = "rgb(29a298)",
				inactive = "rgb(576d74)",
				locked_active = "rgb(db302d)",
				locked_inactive = "rgb(576d74)",
			},
		},
	},
})
