-- Auto-generated by DMS - do not edit manually
-- Migrated from outputs.conf to the Hyprland 0.55+ Lua config format.

hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1080@59.999",
    position = "0x0",
    scale    = 1,
    vrr      = 0,
})
