-- Generated by matugen from ~/.config/matugen/templates/nvim-dms-lualine.lua.
-- Edit the template, not this generated file.

local c = {
  bg = "#001419",
  fg = "#9eabac",
  muted = "#adb7b7",
  surface = "#001419",
  surface_high = "#00202a",
  primary = "#29a298",
  on_primary = "#000c10",
  primary_container = "#103a3c",
  on_primary_container = "#9eabac",
  secondary = "#268bd3",
  on_secondary = "#000c10",
  secondary_container = "#00202a",
  on_secondary_container = "#9eabac",
  tertiary = "#268bd3",
  on_tertiary = "#000c10",
  tertiary_container = "#00202a",
  on_tertiary_container = "#9eabac",
  error = "#db302d",
  on_error = "#601410",
}

local function dms_cache_path()
  local cache_home = vim.env.XDG_CACHE_HOME
  if cache_home == nil or cache_home == "" then
    cache_home = vim.fs.joinpath(vim.env.HOME, ".cache")
  end
  return vim.fs.joinpath(cache_home, "DankMaterialShell", "dms-colors.json")
end

local function read_json(path)
  local file = io.open(path, "r")
  if file == nil then
    return nil
  end

  local ok, parsed = pcall(vim.json.decode, file:read("*a"))
  file:close()
  if ok and type(parsed) == "table" then
    return parsed
  end
  return nil
end

local cache = read_json(dms_cache_path())
local mode_colors = cache and type(cache.colors) == "table" and cache.colors[vim.o.background] or nil
if type(mode_colors) == "table" then
  c.bg = mode_colors.surface or c.bg
  c.fg = mode_colors.on_surface or c.fg
  c.muted = mode_colors.on_surface_variant or c.muted
  c.surface = mode_colors.surface_container or c.surface
  c.surface_high = mode_colors.surface_container_high or c.surface_high
  c.primary = mode_colors.primary or c.primary
  c.on_primary = mode_colors.on_primary or c.on_primary
  c.primary_container = mode_colors.primary_container or c.primary_container
  c.on_primary_container = mode_colors.on_primary_container or c.on_primary_container
  c.secondary = mode_colors.secondary or c.secondary
  c.on_secondary = mode_colors.on_secondary or c.on_secondary
  c.secondary_container = mode_colors.secondary_container or c.secondary_container
  c.on_secondary_container = mode_colors.on_secondary_container or c.on_secondary_container
  c.tertiary = mode_colors.tertiary or c.tertiary
  c.on_tertiary = mode_colors.on_tertiary or c.on_tertiary
  c.tertiary_container = mode_colors.tertiary_container or c.tertiary_container
  c.on_tertiary_container = mode_colors.on_tertiary_container or c.on_tertiary_container
  c.error = mode_colors.error or c.error
  c.on_error = mode_colors.on_error or c.on_error
end

return {
  normal = {
    a = { fg = c.on_primary_container, bg = c.primary_container, gui = "bold" },
    b = { fg = c.fg, bg = c.surface_high },
    c = { fg = c.muted, bg = c.surface },
  },
  insert = {
    a = { fg = c.on_tertiary_container, bg = c.tertiary_container, gui = "bold" },
    b = { fg = c.fg, bg = c.surface_high },
    c = { fg = c.muted, bg = c.surface },
  },
  visual = {
    a = { fg = c.on_secondary_container, bg = c.secondary_container, gui = "bold" },
    b = { fg = c.fg, bg = c.surface_high },
    c = { fg = c.muted, bg = c.surface },
  },
  replace = {
    a = { fg = c.on_error, bg = c.error, gui = "bold" },
    b = { fg = c.fg, bg = c.surface_high },
    c = { fg = c.muted, bg = c.surface },
  },
  command = {
    a = { fg = c.on_primary, bg = c.primary, gui = "bold" },
    b = { fg = c.fg, bg = c.surface_high },
    c = { fg = c.muted, bg = c.surface },
  },
  inactive = {
    a = { fg = c.muted, bg = c.surface },
    b = { fg = c.muted, bg = c.surface },
    c = { fg = c.muted, bg = c.surface },
  },
}
