-- Generated by matugen from ~/.config/matugen/templates/nvim-dms.lua.
-- Edit the template, not this generated file.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "{{mode}}"
vim.o.termguicolors = true
vim.g.colors_name = "dms"

local c = {
  bg = "{{colors.background.default.hex}}",
  fg = "{{colors.on_background.default.hex}}",
  on_surface = "{{colors.on_surface.default.hex}}",
  on_surface_variant = "{{colors.on_surface_variant.default.hex}}",
  surface = "{{colors.surface.default.hex}}",
  surface_low = "{{colors.surface_container_low.default.hex}}",
  surface_mid = "{{colors.surface_container.default.hex}}",
  surface_high = "{{colors.surface_container_high.default.hex}}",
  surface_highest = "{{colors.surface_container_highest.default.hex}}",
  surface_variant = "{{colors.surface_variant.default.hex}}",
  primary = "{{colors.primary.default.hex}}",
  on_primary = "{{colors.on_primary.default.hex}}",
  primary_container = "{{colors.primary_container.default.hex}}",
  on_primary_container = "{{colors.on_primary_container.default.hex}}",
  secondary = "{{colors.secondary.default.hex}}",
  on_secondary = "{{colors.on_secondary.default.hex}}",
  secondary_container = "{{colors.secondary_container.default.hex}}",
  on_secondary_container = "{{colors.on_secondary_container.default.hex}}",
  tertiary = "{{colors.tertiary.default.hex}}",
  on_tertiary = "{{colors.on_tertiary.default.hex}}",
  tertiary_container = "{{colors.tertiary_container.default.hex}}",
  on_tertiary_container = "{{colors.on_tertiary_container.default.hex}}",
  error = "{{colors.error.default.hex}}",
  on_error = "{{colors.on_error.default.hex}}",
  error_container = "{{colors.error_container.default.hex}}",
  on_error_container = "{{colors.on_error_container.default.hex}}",
  outline = "{{colors.outline.default.hex}}",
  outline_variant = "{{colors.outline_variant.default.hex}}",
  accent_bg = "{{colors.primary_container.default.hex}}",
  accent_fg = "{{colors.on_primary_container.default.hex}}",
  source = "{{colors.source_color.default.hex}}",
}

local s = {
  red = "{{base16.base08.default.hex}}",
  orange = "{{base16.base09.default.hex}}",
  yellow = "{{base16.base0a.default.hex}}",
  green = "{{base16.base0b.default.hex}}",
  cyan = "{{base16.base0c.default.hex}}",
  blue = "{{base16.base0d.default.hex}}",
  magenta = "{{base16.base0e.default.hex}}",
  brown = "{{base16.base0f.default.hex}}",
  muted = "{{base16.base04.default.hex}}",
  dim = "{{base16.base03.default.hex}}",
}

local function dms_cache_path()
  local cache_home = vim.env.XDG_CACHE_HOME
  if cache_home == nil or cache_home == "" then
    cache_home = vim.fs.joinpath(vim.env.HOME, ".cache")
  end
  return vim.fs.joinpath(cache_home, "DankMaterialShell", "dms-colors.json")
end

local function read_json(path)
  local file = io.open(path, "r")
  if file == nil then
    return nil
  end

  local ok, parsed = pcall(vim.json.decode, file:read("*a"))
  file:close()
  if ok and type(parsed) == "table" then
    return parsed
  end
  return nil
end

local function pick_role(value)
  if type(value) == "table" then
    return value[vim.o.background] or value.default or value.dark or value.light
  end
  return value
end

local function apply_dms_cache()
  local cache = read_json(dms_cache_path())
  if cache == nil then
    return
  end

  local mode_colors = type(cache.colors) == "table" and cache.colors[vim.o.background] or nil
  if type(mode_colors) == "table" then
    local map = {
      bg = "background",
      fg = "on_surface",
      on_surface = "on_surface",
      on_surface_variant = "on_surface_variant",
      surface = "surface",
      surface_low = "surface_container_low",
      surface_mid = "surface_container",
      surface_high = "surface_container_high",
      surface_highest = "surface_container_highest",
      surface_variant = "surface_variant",
      primary = "primary",
      on_primary = "on_primary",
      primary_container = "primary_container",
      on_primary_container = "on_primary_container",
      secondary = "secondary",
      on_secondary = "on_secondary",
      secondary_container = "secondary_container",
      on_secondary_container = "on_secondary_container",
      tertiary = "tertiary",
      on_tertiary = "on_tertiary",
      tertiary_container = "tertiary_container",
      on_tertiary_container = "on_tertiary_container",
      error = "error",
      on_error = "on_error",
      error_container = "error_container",
      on_error_container = "on_error_container",
      outline = "outline",
      outline_variant = "outline_variant",
      source = "source_color",
    }

    for target, source in pairs(map) do
      if mode_colors[source] ~= nil then
        c[target] = mode_colors[source]
      end
    end

    c.accent_bg = c.primary_container
    c.accent_fg = c.on_primary_container
  end

  if type(cache.dank16) == "table" then
    local function ansi(name, fallback)
      local value = cache.dank16[name]
      return pick_role(value) or fallback
    end

    s.red = ansi("color1", s.red)
    s.orange = ansi("color9", s.orange)
    s.yellow = ansi("color3", s.yellow)
    s.green = ansi("color2", s.green)
    s.cyan = ansi("color6", s.cyan)
    s.blue = ansi("color4", s.blue)
    s.magenta = ansi("color5", s.magenta)
    s.muted = ansi("color8", s.muted)
    s.dim = ansi("color0", s.dim)
    s.fg = ansi("color7", c.fg)
    s.bright_fg = ansi("color15", c.fg)
  end
end

apply_dms_cache()

local function setup_reload_watcher()
  if _G._dms_nvim_theme_watcher then
    return
  end

  local uv = vim.uv or vim.loop
  local timer = uv.new_timer()
  local watchers = {}
  local paths = {
    debug.getinfo(1, "S").source:sub(2),
    dms_cache_path(),
  }

  local function reload()
    timer:stop()
    timer:start(
      120,
      0,
      vim.schedule_wrap(function()
        if vim.g.colors_name == "dms" then
          pcall(vim.cmd.colorscheme, "dms")
        end
      end)
    )
  end

  for _, path in ipairs(paths) do
    if vim.fn.filereadable(path) == 1 then
      local watcher = uv.new_fs_event()
      watcher:start(path, {}, reload)
      table.insert(watchers, watcher)
    end
  end

  _G._dms_nvim_theme_watcher = {
    timer = timer,
    watchers = watchers,
  }
end

setup_reload_watcher()

local transparent = vim.g.dms_transparent ~= false
local bg = transparent and "NONE" or c.bg
local bg_nc = transparent and "NONE" or c.surface
local panel = transparent and "NONE" or c.surface_mid
local panel_high = transparent and "NONE" or c.surface_high

local function set(group, spec)
  vim.api.nvim_set_hl(0, group, spec)
end

set("Normal", { fg = c.fg, bg = bg })
set("NormalNC", { fg = c.fg, bg = bg_nc })
set("EndOfBuffer", { fg = c.surface_variant, bg = bg })
set("SignColumn", { fg = c.outline, bg = bg })
set("FoldColumn", { fg = c.outline, bg = bg })
set("ColorColumn", { bg = c.surface_low })
set("Cursor", { fg = c.on_primary, bg = c.primary })
set("CursorLine", { bg = c.surface_low })
set("CursorLineNr", { fg = c.primary, bg = bg, bold = true })
set("LineNr", { fg = c.outline })
set("WinSeparator", { fg = c.outline_variant, bg = bg })
set("VertSplit", { link = "WinSeparator" })
set("StatusLine", { fg = c.accent_fg, bg = c.accent_bg, bold = true })
set("StatusLineNC", { fg = c.outline, bg = panel })
set("Visual", { fg = c.on_primary_container, bg = c.primary_container })
set("Search", { fg = c.on_tertiary_container, bg = c.tertiary_container })
set("IncSearch", { fg = c.accent_fg, bg = c.accent_bg, bold = true })
set("CurSearch", { link = "IncSearch" })
set("MatchParen", { fg = c.primary, bg = c.surface_high, bold = true })

set("NormalFloat", { fg = c.fg, bg = panel_high })
set("FloatBorder", { fg = c.outline, bg = panel_high })
set("FloatTitle", { fg = c.primary, bg = panel_high, bold = true })
set("Pmenu", { fg = c.fg, bg = panel_high })
set("PmenuSel", { fg = c.on_primary_container, bg = c.primary_container, bold = true })
set("PmenuSbar", { bg = c.surface_variant })
set("PmenuThumb", { bg = c.primary })

set("TabLine", { fg = c.on_surface, bg = panel })
set("TabLineFill", { fg = c.outline, bg = bg })
set("TabLineSel", { fg = c.on_primary_container, bg = c.primary_container, bold = true })
set("Directory", { fg = c.primary, bold = true })
set("Title", { fg = c.primary, bold = true })
set("NonText", { fg = c.outline_variant })
set("Whitespace", { fg = c.outline_variant })
set("SpecialKey", { fg = c.outline })

set("Comment", { fg = c.on_surface_variant, italic = true })
set("Constant", { fg = s.orange })
set("String", { fg = s.green })
set("Character", { fg = s.green })
set("Number", { fg = s.orange })
set("Boolean", { fg = s.orange, bold = true })
set("Float", { fg = s.orange })
set("Identifier", { fg = c.fg })
set("Function", { fg = s.blue, bold = true })
set("Statement", { fg = s.magenta, bold = true })
set("Conditional", { link = "Statement" })
set("Repeat", { link = "Statement" })
set("Label", { fg = s.yellow, bold = true })
set("Operator", { fg = c.on_surface_variant })
set("Keyword", { fg = s.magenta, bold = true })
set("Exception", { fg = s.red, bold = true })
set("PreProc", { fg = s.cyan })
set("Include", { fg = s.magenta })
set("Define", { fg = s.cyan })
set("Macro", { fg = s.cyan, italic = true })
set("Type", { fg = s.yellow, bold = true })
set("StorageClass", { fg = s.magenta })
set("Structure", { fg = s.yellow })
set("Typedef", { fg = s.yellow })
set("Special", { fg = s.cyan })
set("Underlined", { fg = c.primary, underline = true })
set("Todo", { fg = c.on_primary_container, bg = c.primary_container, bold = true })

set("DiagnosticError", { fg = c.error })
set("DiagnosticWarn", { fg = s.yellow })
set("DiagnosticInfo", { fg = s.cyan })
set("DiagnosticHint", { fg = c.primary })
set("DiagnosticOk", { fg = c.primary })
set("DiagnosticVirtualTextError", { fg = c.error, bg = c.error_container })
set("DiagnosticVirtualTextWarn", { fg = s.yellow, bg = c.secondary_container })
set("DiagnosticVirtualTextInfo", { fg = s.cyan, bg = c.tertiary_container })
set("DiagnosticVirtualTextHint", { fg = c.primary, bg = c.primary_container })

set("DiffAdd", { fg = s.green, bg = c.surface_high })
set("DiffChange", { fg = s.yellow, bg = c.surface_high })
set("DiffText", { fg = s.cyan, bg = c.surface_highest, bold = true })
set("DiffDelete", { fg = s.red, bg = c.error_container })

set("@comment", { link = "Comment" })
set("@keyword", { link = "Keyword" })
set("@keyword.function", { link = "Keyword" })
set("@keyword.operator", { fg = s.magenta })
set("@conditional", { link = "Conditional" })
set("@repeat", { link = "Repeat" })
set("@function", { link = "Function" })
set("@function.builtin", { fg = s.blue, bold = true })
set("@function.call", { fg = s.blue })
set("@function.macro", { link = "Macro" })
set("@method", { fg = s.blue })
set("@method.call", { fg = s.blue })
set("@constructor", { fg = s.yellow, bold = true })
set("@string", { link = "String" })
set("@string.escape", { fg = s.cyan })
set("@number", { link = "Number" })
set("@boolean", { link = "Boolean" })
set("@operator", { link = "Operator" })
set("@variable", { fg = c.fg })
set("@variable.builtin", { fg = s.red, italic = true })
set("@variable.parameter", { fg = c.on_surface_variant, italic = true })
set("@constant", { link = "Constant" })
set("@constant.builtin", { fg = s.orange, bold = true })
set("@type", { link = "Type" })
set("@type.builtin", { fg = s.yellow, italic = true })
set("@property", { fg = s.cyan })
set("@field", { fg = s.cyan })
set("@punctuation.bracket", { fg = c.on_surface_variant })
set("@punctuation.delimiter", { fg = c.on_surface_variant })
set("@tag", { fg = c.primary })
set("@tag.attribute", { fg = s.yellow })
set("@tag.delimiter", { fg = c.on_surface_variant })

set("NeoTreeNormal", { fg = c.fg, bg = panel })
set("NeoTreeNormalNC", { link = "NeoTreeNormal" })
set("NeoTreeDirectoryName", { fg = c.primary })
set("NeoTreeDirectoryIcon", { fg = c.primary })
set("NeoTreeRootName", { fg = c.tertiary, bold = true })
set("NeoTreeFileName", { fg = c.fg })
set("NeoTreeFileNameOpened", { fg = c.primary, bold = true })
set("NeoTreeGitAdded", { fg = s.green })
set("NeoTreeGitModified", { fg = s.yellow })
set("NeoTreeGitDeleted", { fg = s.red })
set("NeoTreeGitIgnored", { fg = c.outline, italic = true })
set("NeoTreeWinSeparator", { link = "WinSeparator" })
set("NeoTreeEndOfBuffer", { fg = c.surface_variant, bg = panel })

-- Bufferline uses the same Material selection roles as Visual/PmenuSel. The
-- selected file is therefore obvious across both wallpaper and custom themes.
set("BufferLineFill", { fg = c.on_surface_variant, bg = bg })
set("BufferLineBackground", { fg = c.on_surface, bg = panel })
set("BufferLineBuffer", { fg = c.on_surface, bg = panel })
set("BufferLineBufferVisible", { fg = c.on_surface, bg = panel })
set("BufferLineBufferSelected", { fg = c.on_primary_container, bg = c.primary_container, bold = true })
set("BufferLineIndicatorSelected", { fg = c.on_primary_container, bg = c.primary_container, bold = true })
set("BufferLineCloseButton", { fg = c.on_surface_variant, bg = panel })
set("BufferLineCloseButtonVisible", { fg = c.on_surface, bg = panel })
set("BufferLineCloseButtonSelected", { fg = c.on_primary_container, bg = c.primary_container })
set("BufferLineModified", { fg = c.tertiary, bg = panel })
set("BufferLineModifiedVisible", { fg = c.tertiary, bg = panel })
set("BufferLineModifiedSelected", { fg = c.on_primary_container, bg = c.primary_container, bold = true })
set("BufferLineSeparator", { fg = c.surface, bg = panel })
set("BufferLineSeparatorVisible", { fg = c.surface, bg = c.surface_high })
set("BufferLineSeparatorSelected", { fg = c.primary_container, bg = bg })

set("TelescopeNormal", { fg = c.fg, bg = panel })
set("TelescopeBorder", { fg = c.outline, bg = panel })
set("TelescopePromptNormal", { fg = c.fg, bg = panel_high })
set("TelescopePromptBorder", { fg = c.primary, bg = panel_high })
set("TelescopePromptTitle", { fg = c.accent_fg, bg = c.accent_bg, bold = true })
set("TelescopePreviewTitle", { fg = c.on_secondary_container, bg = c.secondary_container, bold = true })
set("TelescopeResultsTitle", { fg = c.on_tertiary_container, bg = c.tertiary_container, bold = true })
set("TelescopeSelection", { fg = c.on_primary_container, bg = c.primary_container, bold = true })
set("TelescopeMatching", { fg = c.primary, bold = true })

set("WhichKeyFloat", { bg = panel_high })
set("WhichKey", { fg = c.primary, bold = true })
set("WhichKeyDesc", { fg = c.fg })
set("WhichKeyGroup", { fg = c.tertiary })
set("WhichKeySeparator", { fg = c.outline })

set("SnacksDashboardHeader", { fg = c.primary, bold = true })
set("SnacksDashboardIcon", { fg = c.primary })
set("SnacksDashboardKey", { fg = s.yellow, bold = true })
set("SnacksDashboardDesc", { fg = c.fg })
set("SnacksDashboardDir", { fg = s.blue })
set("SnacksDashboardFooter", { fg = c.outline, italic = true })
set("SnacksPicker", { fg = c.fg, bg = panel })
set("SnacksPickerBorder", { fg = c.outline, bg = panel })
set("SnacksPickerMatch", { fg = c.primary, bold = true })
set("SnacksPickerCursorLine", { bg = c.primary_container })

set("NoiceCmdlinePopup", { fg = c.fg, bg = panel_high })
set("NoiceCmdlinePopupBorder", { fg = c.primary, bg = panel_high })
set("NoiceCmdlinePopupTitle", { fg = c.primary, bg = panel_high, bold = true })
set("NoiceCmdlineIcon", { fg = c.primary })
set("NotifyINFOBody", { fg = c.fg, bg = panel_high })
set("NotifyWARNBody", { fg = c.fg, bg = panel_high })
set("NotifyERRORBody", { fg = c.fg, bg = panel_high })
set("NotifyDEBUGBody", { fg = c.fg, bg = panel_high })
set("NotifyTRACEBody", { fg = c.fg, bg = panel_high })
set("NotifyINFOBorder", { fg = s.cyan, bg = panel_high })
set("NotifyWARNBorder", { fg = s.yellow, bg = panel_high })
set("NotifyERRORBorder", { fg = c.error, bg = panel_high })
set("NotifyDEBUGBorder", { fg = c.outline, bg = panel_high })
set("NotifyTRACEBorder", { fg = c.primary, bg = panel_high })

set("GitSignsAdd", { fg = s.green })
set("GitSignsChange", { fg = s.yellow })
set("GitSignsDelete", { fg = s.red })
set("LazyNormal", { fg = c.fg, bg = panel })
set("MasonNormal", { fg = c.fg, bg = panel })
set("BlinkCmpMenu", { fg = c.fg, bg = panel_high })
set("BlinkCmpMenuSelection", { fg = c.on_primary_container, bg = c.primary_container })
set("BlinkCmpLabelMatch", { fg = c.primary, bold = true })

vim.g.terminal_color_0 = s.dim
vim.g.terminal_color_1 = s.red
vim.g.terminal_color_2 = s.green
vim.g.terminal_color_3 = s.yellow
vim.g.terminal_color_4 = s.blue
vim.g.terminal_color_5 = s.magenta
vim.g.terminal_color_6 = s.cyan
vim.g.terminal_color_7 = s.fg or "{{base16.base05.default.hex}}"
vim.g.terminal_color_8 = s.muted
vim.g.terminal_color_9 = s.red
vim.g.terminal_color_10 = s.green
vim.g.terminal_color_11 = s.yellow
vim.g.terminal_color_12 = s.blue
vim.g.terminal_color_13 = s.magenta
vim.g.terminal_color_14 = s.cyan
vim.g.terminal_color_15 = s.bright_fg or "{{base16.base07.default.hex}}"
