# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(2B2931)
$foreground = rgb(FDF2C1)
$color0 = rgb(504E57)
$color1 = rgb(1B2645)
$color2 = rgb(212745)
$color3 = rgb(553043)
$color4 = rgb(16526D)
$color5 = rgb(823842)
$color6 = rgb(BBA33A)
$color7 = rgb(F4E49E)
$color8 = rgb(AB9F6F)
$color9 = rgb(24325C)
$color10 = rgb(2C345C)
$color11 = rgb(71405A)
$color12 = rgb(1D6E91)
$color13 = rgb(AD4B58)
$color14 = rgb(FAD94E)
$color15 = rgb(F4E49E)
