# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(2D2128)
$foreground = rgb(E7D0BC)
$color0 = rgb(53474F)
$color1 = rgb(3F2034)
$color2 = rgb(3F2235)
$color3 = rgb(62262A)
$color4 = rgb(464244)
$color5 = rgb(464646)
$color6 = rgb(8B5A2F)
$color7 = rgb(D4B397)
$color8 = rgb(947D69)
$color9 = rgb(532A45)
$color10 = rgb(542D46)
$color11 = rgb(833338)
$color12 = rgb(5D585B)
$color13 = rgb(5E5E5E)
$color14 = rgb(BA783F)
$color15 = rgb(D4B397)
