# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1C2021)
$foreground = rgb(EDF7D8)
$color0 = rgb(424647)
$color1 = rgb(2A523B)
$color2 = rgb(2A523B)
$color3 = rgb(5B8564)
$color4 = rgb(5B8564)
$color5 = rgb(5B8564)
$color6 = rgb(98AD6D)
$color7 = rgb(DDEBC0)
$color8 = rgb(9AA486)
$color9 = rgb(386D4F)
$color10 = rgb(386D4F)
$color11 = rgb(79B186)
$color12 = rgb(79B186)
$color13 = rgb(79B186)
$color14 = rgb(CBE791)
$color15 = rgb(DDEBC0)
